# Generated by Django 4.1 on 2022-09-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_product_feedback_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
