# Generated by Django 3.2.16 on 2023-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
